/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime posture */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI contract */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI YAML */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session identity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current identity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthIdentityItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout acknowledgement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured clusters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a cluster */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClusterCreateRequest"];
                };
            };
            responses: {
                /** @description Created cluster */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cluster */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update cluster */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClusterUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated cluster */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/swarm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cluster posture */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Swarm posture */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SwarmInfoItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List diagnostics findings */
        get: {
            parameters: {
                query?: {
                    severity?: components["schemas"]["Severity"];
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Diagnostics findings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FindingListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Incidents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create incident */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IncidentCreateRequest"];
                };
            };
            responses: {
                /** @description Created incident */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get incident */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Incident detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update incident */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IncidentUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated incident */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/incidents/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve incident */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved incident */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit entries */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntryListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/ops/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cluster metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operational metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsMetricsItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/ops/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cluster insights */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operational insights */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsInsightsItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List action runs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Action runs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionRunListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/actions/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute or queue an action */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActionExecuteRequest"];
                };
            };
            responses: {
                /** @description Action outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionOutcomeItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approval requests */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ApprovalStatus"];
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approval requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApprovalRequestListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve pending action */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approval outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionOutcomeItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/approvals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject pending action */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rejection outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionOutcomeItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/assistant/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assistant sessions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Assistant sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantSessionListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create assistant session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AssistantSessionCreateRequest"];
                };
            };
            responses: {
                /** @description Created assistant session */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantSessionItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/assistant/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get assistant session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Assistant session detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantSessionItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream assistant response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantChatRequest"];
                };
            };
            responses: {
                /** @description Event stream with context, insights, citations, and message payloads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            code: string;
        };
        ListMeta: {
            total: number;
        };
        /** @enum {string} */
        Role: "viewer" | "operator" | "admin";
        /** @enum {string} */
        AppMode: "dev" | "demo" | "prod";
        /** @enum {string} */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /** @enum {string} */
        FreshnessState: "live" | "stale" | "disconnected";
        /** @enum {string} */
        ClusterConnectionMode: "direct" | "demo";
        /** @enum {string} */
        IncidentStatus: "open" | "investigating" | "mitigating" | "resolved";
        /** @enum {string} */
        ActionStatus: "success" | "failed" | "dry_run" | "blocked" | "pending_approval";
        /** @enum {string} */
        ApprovalStatus: "pending" | "approved" | "rejected";
        /** @enum {string} */
        AuditResult: "success" | "failed" | "rejected" | "pending_approval";
        RiskAssessment: {
            score: number;
            confidence: number;
            factors: string[];
            source: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ClusterHealth: {
            freshness: components["schemas"]["FreshnessState"];
            /** Format: date-time */
            lastSyncAt?: string;
            lastSyncError?: string;
            managers: number;
            workers: number;
            reachable: boolean;
        };
        Cluster: {
            id: string;
            name: string;
            dockerHost: string;
            connectionMode: components["schemas"]["ClusterConnectionMode"];
            tlsEnabled: boolean;
            certRef: string;
            enabled: boolean;
            default: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            health: components["schemas"]["ClusterHealth"];
        };
        ClusterCreateRequest: {
            name: string;
            dockerHost: string;
            connectionMode?: components["schemas"]["ClusterConnectionMode"];
            tlsEnabled?: boolean;
            certRef?: string;
            enabled?: boolean;
            default?: boolean;
        };
        ClusterUpdateRequest: {
            name?: string;
            dockerHost?: string;
            connectionMode?: components["schemas"]["ClusterConnectionMode"];
            tlsEnabled?: boolean;
            certRef?: string;
            enabled?: boolean;
            default?: boolean;
        };
        AuthIdentity: {
            authenticated: boolean;
            username?: string;
            role?: components["schemas"]["Role"];
            provider?: string;
            groups?: string[];
            csrfToken?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        SwarmInfo: {
            clusterID: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            managers: number;
            workers: number;
            quorumHealthy: boolean;
            /** @enum {string} */
            raftState: "healthy" | "degraded" | "single" | "unknown";
            mode: components["schemas"]["AppMode"];
            writeEnabled: boolean;
            freshness: components["schemas"]["FreshnessState"];
            /** Format: date-time */
            lastSyncAt: string;
            syncError?: string;
            risk: components["schemas"]["RiskAssessment"];
        };
        Finding: {
            id: string;
            severity: components["schemas"]["Severity"];
            resource: string;
            scope: string;
            message: string;
            evidence: string[];
            recommendation: string;
            source: string;
            /** Format: date-time */
            detectedAt: string;
        };
        RunbookStep: {
            id: string;
            title: string;
            description: string;
            /** @enum {string} */
            status: "pending" | "in_progress" | "done" | "skipped";
            completedBy?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        TimelineEntry: {
            id: string;
            actor: string;
            action: string;
            note: string;
            /** Format: date-time */
            timestamp: string;
        };
        Incident: {
            id: string;
            clusterID?: string;
            title: string;
            description: string;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["IncidentStatus"];
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            resolvedAt?: string;
            affectedServices: string[];
            diagnosticRefs: string[];
            runbookSteps: components["schemas"]["RunbookStep"][];
            timeline: components["schemas"]["TimelineEntry"][];
        };
        IncidentCreateRequest: {
            title: string;
            description: string;
            severity: components["schemas"]["Severity"];
            affectedServices?: string[];
            diagnosticRefs?: string[];
        };
        IncidentUpdateRequest: {
            title?: string;
            description?: string;
            severity?: components["schemas"]["Severity"];
            status?: components["schemas"]["IncidentStatus"];
            affectedServices?: string[];
            diagnosticRefs?: string[];
        };
        AuditEntry: {
            id: string;
            clusterID?: string;
            actionRunID?: string;
            actor: string;
            role: components["schemas"]["Role"];
            action: string;
            resource: string;
            resourceID: string;
            beforeSpec?: {
                [key: string]: unknown;
            };
            afterSpec?: {
                [key: string]: unknown;
            };
            result: components["schemas"]["AuditResult"];
            reason?: string;
            /** Format: date-time */
            timestamp: string;
        };
        ActionOutcome: {
            id?: string;
            clusterID?: string;
            action: string;
            resource: string;
            resourceID: string;
            reason?: string;
            status: components["schemas"]["ActionStatus"];
            mode: string;
            executed: boolean;
            approvalID?: string;
            approvalRequired?: boolean;
            message: string;
            blockedReason?: string;
            impact?: string;
            plan?: string[];
            auditID?: string;
            /** Format: date-time */
            timestamp: string;
        };
        ActionRun: {
            id: string;
            clusterID: string;
            action: string;
            resource: string;
            resourceID: string;
            requestedBy: string;
            requestedRole: components["schemas"]["Role"];
            reason: string;
            status: components["schemas"]["ActionStatus"];
            mode: string;
            executed: boolean;
            approvalRequired: boolean;
            approvalID?: string;
            auditID?: string;
            message?: string;
            blockedReason?: string;
            impact?: string;
            plan?: string[];
            params?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        ApprovalRequest: {
            id: string;
            clusterID: string;
            actionRunID: string;
            action: string;
            resource: string;
            resourceID: string;
            requestedBy: string;
            requestedRole: components["schemas"]["Role"];
            reason: string;
            status: components["schemas"]["ApprovalStatus"];
            resolutionReason?: string;
            resolvedBy?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        AssistantCitation: {
            id: string;
            kind: string;
            title: string;
            locator: string;
            snippet?: string;
        };
        AssistantActionProposal: {
            title: string;
            action: string;
            resource?: string;
            resourceID?: string;
            reason: string;
            params?: {
                [key: string]: unknown;
            };
            requiresApproval: boolean;
        };
        AssistantMessage: {
            id: string;
            sessionID: string;
            role: string;
            content: string;
            citations?: components["schemas"]["AssistantCitation"][];
            actionProposals?: components["schemas"]["AssistantActionProposal"][];
            /** Format: date-time */
            createdAt: string;
        };
        AssistantSession: {
            id: string;
            clusterID: string;
            incidentID?: string;
            title: string;
            createdBy: string;
            lastSummary?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            messages?: components["schemas"]["AssistantMessage"][];
        };
        AssistantSessionCreateRequest: {
            title?: string;
            incidentID?: string;
        };
        AssistantChatRequest: {
            prompt: string;
            sessionID?: string;
            incidentID?: string;
        };
        ActionExecuteRequest: {
            action: string;
            resource?: string;
            resourceID?: string;
            reason: string;
            params?: {
                [key: string]: unknown;
            };
        };
        OpsMetricPoint: {
            /** Format: date-time */
            timestamp: string;
            healthyRatio: number;
            managersOnline: number;
            workersOnline: number;
            runningTasks: number;
            failedTasks: number;
            restartCount: number;
            critical: number;
            warning: number;
            riskScore: number;
        };
        ServiceRisk: {
            service: string;
            score: number;
            reasons: string[];
            actionability: string;
        };
        OpsMetrics: {
            freshness: components["schemas"]["FreshnessState"];
            /** Format: date-time */
            lastUpdated: string;
            series: components["schemas"]["OpsMetricPoint"][];
            serviceRisk: components["schemas"]["ServiceRisk"][];
        };
        InsightHypothesis: {
            title: string;
            why: string;
            confidence: number;
        };
        InsightAction: {
            title: string;
            description: string;
            endpointHint: string;
            priority: number;
            actionability: string;
        };
        OpsInsights: {
            summary: string;
            risk: components["schemas"]["RiskAssessment"];
            freshness: components["schemas"]["FreshnessState"];
            hypotheses: components["schemas"]["InsightHypothesis"][];
            actions: components["schemas"]["InsightAction"][];
            /** Format: date-time */
            generatedAt: string;
            provider: string;
            sourceStrategy: string;
        };
        OkResult: {
            ok: boolean;
        };
        AuthIdentityItemResponse: {
            data: components["schemas"]["AuthIdentity"];
        };
        ClusterItemResponse: {
            data: components["schemas"]["Cluster"];
        };
        ClusterListResponse: {
            data: components["schemas"]["Cluster"][];
            meta: components["schemas"]["ListMeta"];
        };
        SwarmInfoItemResponse: {
            data: components["schemas"]["SwarmInfo"];
        };
        FindingListResponse: {
            data: components["schemas"]["Finding"][];
            meta: components["schemas"]["ListMeta"];
        };
        IncidentItemResponse: {
            data: components["schemas"]["Incident"];
        };
        IncidentListResponse: {
            data: components["schemas"]["Incident"][];
            meta: components["schemas"]["ListMeta"];
        };
        AuditEntryListResponse: {
            data: components["schemas"]["AuditEntry"][];
            meta: components["schemas"]["ListMeta"];
        };
        OpsMetricsItemResponse: {
            data: components["schemas"]["OpsMetrics"];
        };
        OpsInsightsItemResponse: {
            data: components["schemas"]["OpsInsights"];
        };
        ActionOutcomeItemResponse: {
            data: components["schemas"]["ActionOutcome"];
        };
        ActionRunListResponse: {
            data: components["schemas"]["ActionRun"][];
            meta: components["schemas"]["ListMeta"];
        };
        ApprovalRequestListResponse: {
            data: components["schemas"]["ApprovalRequest"][];
            meta: components["schemas"]["ListMeta"];
        };
        AssistantSessionItemResponse: {
            data: components["schemas"]["AssistantSession"];
        };
        AssistantSessionListResponse: {
            data: components["schemas"]["AssistantSession"][];
            meta: components["schemas"]["ListMeta"];
        };
        OkItemResponse: {
            data: components["schemas"]["OkResult"];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ClusterID: string;
        EntityID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
