/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime posture */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI contract */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI YAML */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session identity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current identity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthIdentityItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout acknowledgement */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OkItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured clusters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a cluster */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClusterCreateRequest"];
                };
            };
            responses: {
                /** @description Created cluster */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cluster */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update cluster */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClusterUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated cluster */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/swarm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cluster posture */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Swarm posture */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SwarmInfoItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List nodes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nodes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NodeListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get node */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Node detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NodeItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/stacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stacks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stacks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StackListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/stacks/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get stack */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stack detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StackItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List services */
        get: {
            parameters: {
                query?: {
                    stack?: string;
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Services */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get service */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks */
        get: {
            parameters: {
                query?: {
                    service?: string;
                    node?: string;
                    state?: components["schemas"]["TaskState"];
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List networks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Networks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NetworkListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List volumes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Volumes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VolumeListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List secrets */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Secrets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SecretListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Configs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent cluster events */
        get: {
            parameters: {
                query?: {
                    type?: string;
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SwarmEventListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/stream/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream cluster events */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List diagnostics findings */
        get: {
            parameters: {
                query?: {
                    severity?: components["schemas"]["Severity"];
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Diagnostics findings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FindingListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Incidents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create incident */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IncidentCreateRequest"];
                };
            };
            responses: {
                /** @description Created incident */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get incident */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Incident detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Update incident */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IncidentUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated incident */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/incidents/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve incident */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved incident */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit entries */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntryListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/ops/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cluster metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operational metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsMetricsItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/ops/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cluster insights */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operational insights */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsInsightsItemResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List action runs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Action runs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionRunListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/actions/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute or queue an action */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActionExecuteRequest"];
                };
            };
            responses: {
                /** @description Action outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionOutcomeItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approval requests */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ApprovalStatus"];
                };
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approval requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApprovalRequestListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve pending action */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Approval outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionOutcomeItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/approvals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject pending action */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rejection outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionOutcomeItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/assistant/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assistant sessions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Assistant sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantSessionListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create assistant session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AssistantSessionCreateRequest"];
                };
            };
            responses: {
                /** @description Created assistant session */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantSessionItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/assistant/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get assistant session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                    id: components["parameters"]["EntityID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Assistant session detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantSessionItemResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterID}/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream assistant response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterID: components["parameters"]["ClusterID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantChatRequest"];
                };
            };
            responses: {
                /** @description Event stream with context, insights, citations, and message payloads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            code: string;
        };
        ListMeta: {
            total: number;
        };
        /** @enum {string} */
        Role: "viewer" | "operator" | "admin";
        /** @enum {string} */
        AppMode: "dev" | "demo" | "prod";
        /** @enum {string} */
        Severity: "critical" | "high" | "medium" | "low" | "info";
        /** @enum {string} */
        FreshnessState: "live" | "stale" | "disconnected";
        /** @enum {string} */
        ClusterConnectionMode: "direct" | "demo";
        /** @enum {string} */
        NodeRole: "manager" | "worker";
        /** @enum {string} */
        NodeAvailability: "active" | "pause" | "drain";
        /** @enum {string} */
        NodeState: "ready" | "down" | "disconnected" | "unknown";
        /** @enum {string} */
        Reachability: "reachable" | "unreachable";
        /** @enum {string} */
        ServiceMode: "replicated" | "global";
        /** @enum {string} */
        UpdateState: "updating" | "paused" | "completed" | "rollback_started" | "rollback_paused" | "rollback_completed" | "";
        /** @enum {string} */
        TaskState: "new" | "pending" | "assigned" | "accepted" | "preparing" | "ready" | "starting" | "running" | "complete" | "shutdown" | "failed" | "rejected" | "remove" | "orphaned";
        /** @enum {string} */
        NetworkScope: "swarm" | "local" | "global";
        /** @enum {string} */
        IncidentStatus: "open" | "investigating" | "mitigating" | "resolved";
        /** @enum {string} */
        ActionStatus: "success" | "failed" | "dry_run" | "blocked" | "pending_approval";
        /** @enum {string} */
        ApprovalStatus: "pending" | "approved" | "rejected";
        /** @enum {string} */
        AuditResult: "success" | "failed" | "rejected" | "pending_approval";
        RiskAssessment: {
            score: number;
            confidence: number;
            factors: string[];
            source: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ClusterHealth: {
            freshness: components["schemas"]["FreshnessState"];
            /** Format: date-time */
            lastSyncAt?: string;
            lastSyncError?: string;
            managers: number;
            workers: number;
            reachable: boolean;
        };
        Cluster: {
            id: string;
            name: string;
            dockerHost: string;
            connectionMode: components["schemas"]["ClusterConnectionMode"];
            tlsEnabled: boolean;
            certRef: string;
            enabled: boolean;
            default: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            health: components["schemas"]["ClusterHealth"];
        };
        ClusterCreateRequest: {
            name: string;
            dockerHost: string;
            connectionMode?: components["schemas"]["ClusterConnectionMode"];
            tlsEnabled?: boolean;
            certRef?: string;
            enabled?: boolean;
            default?: boolean;
        };
        ClusterUpdateRequest: {
            name?: string;
            dockerHost?: string;
            connectionMode?: components["schemas"]["ClusterConnectionMode"];
            tlsEnabled?: boolean;
            certRef?: string;
            enabled?: boolean;
            default?: boolean;
        };
        AuthIdentity: {
            authenticated: boolean;
            username?: string;
            role?: components["schemas"]["Role"];
            provider?: string;
            groups?: string[];
            csrfToken?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        SwarmInfo: {
            clusterID: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            managers: number;
            workers: number;
            quorumHealthy: boolean;
            /** @enum {string} */
            raftState: "healthy" | "degraded" | "single" | "unknown";
            mode: components["schemas"]["AppMode"];
            writeEnabled: boolean;
            freshness: components["schemas"]["FreshnessState"];
            /** Format: date-time */
            lastSyncAt: string;
            syncError?: string;
            risk: components["schemas"]["RiskAssessment"];
        };
        ManagerStatus: {
            leader: boolean;
            reachability: components["schemas"]["Reachability"];
        };
        Node: {
            id: string;
            hostname: string;
            role: components["schemas"]["NodeRole"];
            availability: components["schemas"]["NodeAvailability"];
            state: components["schemas"]["NodeState"];
            labels: {
                [key: string]: string;
            };
            /** Format: int64 */
            cpuTotal: number;
            /** Format: int64 */
            cpuReserved: number;
            /** Format: int64 */
            memTotal: number;
            /** Format: int64 */
            memReserved: number;
            runningTasks: number;
            managerStatus?: components["schemas"]["ManagerStatus"];
            engineVersion: string;
            addr: string;
        };
        Stack: {
            name: string;
            serviceCount: number;
            runningServices: number;
            totalReplicas: number;
            runningReplicas: number;
            healthScore: number;
        };
        PublishedPort: {
            publishedPort: number;
            targetPort: number;
            protocol: string;
        };
        Service: {
            id: string;
            name: string;
            stack: string;
            image: string;
            mode: components["schemas"]["ServiceMode"];
            desiredReplicas: number;
            runningTasks: number;
            failedTasks: number;
            updateState: components["schemas"]["UpdateState"];
            /** Format: int64 */
            updateParallelism: number;
            updateDelay: string;
            updateFailureAction: string;
            /** Format: int64 */
            rollbackParallelism: number;
            rollbackDelay: string;
            constraints: string[];
            preferences: string[];
            publishedPorts: components["schemas"]["PublishedPort"][];
            secretRefs: string[];
            configRefs: string[];
            networkRefs: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Task: {
            id: string;
            serviceID: string;
            serviceName: string;
            nodeID: string;
            nodeHostname: string;
            desiredState: components["schemas"]["TaskState"];
            currentState: components["schemas"]["TaskState"];
            exitCode: number;
            error: string;
            image: string;
            restartCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Network: {
            id: string;
            name: string;
            driver: string;
            scope: components["schemas"]["NetworkScope"];
            subnet: string;
            attachable: boolean;
            ingress: boolean;
            serviceCount: number;
        };
        Volume: {
            name: string;
            driver: string;
            scope: string;
            mountpoint: string;
            labels: {
                [key: string]: string;
            };
        };
        Secret: {
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            serviceRefs: string[];
        };
        Config: {
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            serviceRefs: string[];
        };
        SwarmEvent: {
            type: string;
            action: string;
            actor: string;
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
        Finding: {
            id: string;
            severity: components["schemas"]["Severity"];
            resource: string;
            scope: string;
            message: string;
            evidence: string[];
            recommendation: string;
            source: string;
            /** Format: date-time */
            detectedAt: string;
        };
        RunbookStep: {
            id: string;
            title: string;
            description: string;
            /** @enum {string} */
            status: "pending" | "in_progress" | "done" | "skipped";
            completedBy?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        TimelineEntry: {
            id: string;
            actor: string;
            action: string;
            note: string;
            /** Format: date-time */
            timestamp: string;
        };
        Incident: {
            id: string;
            clusterID?: string;
            title: string;
            description: string;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["IncidentStatus"];
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            resolvedAt?: string;
            affectedServices: string[];
            diagnosticRefs: string[];
            runbookSteps: components["schemas"]["RunbookStep"][];
            timeline: components["schemas"]["TimelineEntry"][];
        };
        IncidentCreateRequest: {
            title: string;
            description: string;
            severity: components["schemas"]["Severity"];
            affectedServices?: string[];
            diagnosticRefs?: string[];
        };
        IncidentUpdateRequest: {
            title?: string;
            description?: string;
            severity?: components["schemas"]["Severity"];
            status?: components["schemas"]["IncidentStatus"];
            affectedServices?: string[];
            diagnosticRefs?: string[];
        };
        AuditEntry: {
            id: string;
            clusterID?: string;
            actionRunID?: string;
            actor: string;
            role: components["schemas"]["Role"];
            action: string;
            resource: string;
            resourceID: string;
            beforeSpec?: {
                [key: string]: unknown;
            };
            afterSpec?: {
                [key: string]: unknown;
            };
            result: components["schemas"]["AuditResult"];
            reason?: string;
            /** Format: date-time */
            timestamp: string;
        };
        ActionOutcome: {
            id?: string;
            clusterID?: string;
            action: string;
            resource: string;
            resourceID: string;
            reason?: string;
            status: components["schemas"]["ActionStatus"];
            mode: string;
            executed: boolean;
            approvalID?: string;
            approvalRequired?: boolean;
            message: string;
            blockedReason?: string;
            impact?: string;
            plan?: string[];
            auditID?: string;
            /** Format: date-time */
            timestamp: string;
        };
        ActionRun: {
            id: string;
            clusterID: string;
            action: string;
            resource: string;
            resourceID: string;
            requestedBy: string;
            requestedRole: components["schemas"]["Role"];
            reason: string;
            status: components["schemas"]["ActionStatus"];
            mode: string;
            executed: boolean;
            approvalRequired: boolean;
            approvalID?: string;
            auditID?: string;
            message?: string;
            blockedReason?: string;
            impact?: string;
            plan?: string[];
            params?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        ApprovalRequest: {
            id: string;
            clusterID: string;
            actionRunID: string;
            action: string;
            resource: string;
            resourceID: string;
            requestedBy: string;
            requestedRole: components["schemas"]["Role"];
            reason: string;
            status: components["schemas"]["ApprovalStatus"];
            resolutionReason?: string;
            resolvedBy?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt?: string;
        };
        AssistantCitation: {
            id: string;
            kind: string;
            title: string;
            locator: string;
            snippet?: string;
        };
        AssistantActionProposal: {
            title: string;
            action: string;
            resource?: string;
            resourceID?: string;
            reason: string;
            params?: {
                [key: string]: unknown;
            };
            requiresApproval: boolean;
        };
        AssistantMessage: {
            id: string;
            sessionID: string;
            role: string;
            content: string;
            citations?: components["schemas"]["AssistantCitation"][];
            actionProposals?: components["schemas"]["AssistantActionProposal"][];
            /** Format: date-time */
            createdAt: string;
        };
        AssistantSession: {
            id: string;
            clusterID: string;
            incidentID?: string;
            title: string;
            createdBy: string;
            lastSummary?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            messages?: components["schemas"]["AssistantMessage"][];
        };
        AssistantSessionCreateRequest: {
            title?: string;
            incidentID?: string;
        };
        AssistantChatRequest: {
            prompt: string;
            sessionID?: string;
            incidentID?: string;
        };
        ActionExecuteRequest: {
            action: string;
            resource?: string;
            resourceID?: string;
            reason: string;
            params?: {
                [key: string]: unknown;
            };
        };
        OpsMetricPoint: {
            /** Format: date-time */
            timestamp: string;
            healthyRatio: number;
            managersOnline: number;
            workersOnline: number;
            runningTasks: number;
            failedTasks: number;
            restartCount: number;
            critical: number;
            warning: number;
            riskScore: number;
        };
        ServiceRisk: {
            service: string;
            score: number;
            reasons: string[];
            actionability: string;
        };
        OpsMetrics: {
            freshness: components["schemas"]["FreshnessState"];
            /** Format: date-time */
            lastUpdated: string;
            series: components["schemas"]["OpsMetricPoint"][];
            serviceRisk: components["schemas"]["ServiceRisk"][];
        };
        InsightHypothesis: {
            title: string;
            why: string;
            confidence: number;
        };
        InsightAction: {
            title: string;
            description: string;
            endpointHint: string;
            priority: number;
            actionability: string;
        };
        OpsInsights: {
            summary: string;
            risk: components["schemas"]["RiskAssessment"];
            freshness: components["schemas"]["FreshnessState"];
            hypotheses: components["schemas"]["InsightHypothesis"][];
            actions: components["schemas"]["InsightAction"][];
            /** Format: date-time */
            generatedAt: string;
            provider: string;
            sourceStrategy: string;
        };
        OkResult: {
            ok: boolean;
        };
        AuthIdentityItemResponse: {
            data: components["schemas"]["AuthIdentity"];
        };
        ClusterItemResponse: {
            data: components["schemas"]["Cluster"];
        };
        ClusterListResponse: {
            data: components["schemas"]["Cluster"][];
            meta: components["schemas"]["ListMeta"];
        };
        SwarmInfoItemResponse: {
            data: components["schemas"]["SwarmInfo"];
        };
        NodeItemResponse: {
            data: components["schemas"]["Node"];
        };
        NodeListResponse: {
            data: components["schemas"]["Node"][];
            meta: components["schemas"]["ListMeta"];
        };
        StackItemResponse: {
            data: components["schemas"]["Stack"];
        };
        StackListResponse: {
            data: components["schemas"]["Stack"][];
            meta: components["schemas"]["ListMeta"];
        };
        ServiceItemResponse: {
            data: components["schemas"]["Service"];
        };
        ServiceListResponse: {
            data: components["schemas"]["Service"][];
            meta: components["schemas"]["ListMeta"];
        };
        TaskItemResponse: {
            data: components["schemas"]["Task"];
        };
        TaskListResponse: {
            data: components["schemas"]["Task"][];
            meta: components["schemas"]["ListMeta"];
        };
        NetworkListResponse: {
            data: components["schemas"]["Network"][];
            meta: components["schemas"]["ListMeta"];
        };
        VolumeListResponse: {
            data: components["schemas"]["Volume"][];
            meta: components["schemas"]["ListMeta"];
        };
        SecretListResponse: {
            data: components["schemas"]["Secret"][];
            meta: components["schemas"]["ListMeta"];
        };
        ConfigListResponse: {
            data: components["schemas"]["Config"][];
            meta: components["schemas"]["ListMeta"];
        };
        SwarmEventListResponse: {
            data: components["schemas"]["SwarmEvent"][];
            meta: components["schemas"]["ListMeta"];
        };
        FindingListResponse: {
            data: components["schemas"]["Finding"][];
            meta: components["schemas"]["ListMeta"];
        };
        IncidentItemResponse: {
            data: components["schemas"]["Incident"];
        };
        IncidentListResponse: {
            data: components["schemas"]["Incident"][];
            meta: components["schemas"]["ListMeta"];
        };
        AuditEntryListResponse: {
            data: components["schemas"]["AuditEntry"][];
            meta: components["schemas"]["ListMeta"];
        };
        OpsMetricsItemResponse: {
            data: components["schemas"]["OpsMetrics"];
        };
        OpsInsightsItemResponse: {
            data: components["schemas"]["OpsInsights"];
        };
        ActionOutcomeItemResponse: {
            data: components["schemas"]["ActionOutcome"];
        };
        ActionRunListResponse: {
            data: components["schemas"]["ActionRun"][];
            meta: components["schemas"]["ListMeta"];
        };
        ApprovalRequestListResponse: {
            data: components["schemas"]["ApprovalRequest"][];
            meta: components["schemas"]["ListMeta"];
        };
        AssistantSessionItemResponse: {
            data: components["schemas"]["AssistantSession"];
        };
        AssistantSessionListResponse: {
            data: components["schemas"]["AssistantSession"][];
            meta: components["schemas"]["ListMeta"];
        };
        OkItemResponse: {
            data: components["schemas"]["OkResult"];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ClusterID: string;
        EntityID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
